name: googlemaps
description: "Implementing google maps API."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  arcore_flutter_plugin:
    git:
      url: https://github.com/giandifra/arcore_flutter_plugin.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
